/**
 * Adapter to transform generated files into Sandpack-compatible format
 */

import type { SandpackFiles } from "@codesandbox/sandpack-react";
import type { GeneratedFile } from "./schemas";

/**
 * Default package.json for React apps
 */
const DEFAULT_PACKAGE_JSON = {
  name: "generated-app",
  version: "1.0.0",
  description: "Generated by VibeSDK",
  main: "index.tsx",
  scripts: {
    start: "react-scripts start",
    build: "react-scripts build",
  },
  dependencies: {
    react: "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "^5.0.1",
  },
  devDependencies: {
    "@types/react": "^18.2.0",
    "@types/react-dom": "^18.2.0",
    typescript: "^5.0.0",
  },
};

/**
 * Default App.tsx if none is provided
 */
const DEFAULT_APP = `export default function App() {
  return (
    <div style={{ padding: '20px', fontFamily: 'system-ui' }}>
      <h1>Welcome to VibeSDK</h1>
      <p>Your generated app will appear here.</p>
    </div>
  );
}`;

/**
 * Default index.tsx entry point
 */
const DEFAULT_INDEX = `import React, { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";

import App from "./App";

const root = createRoot(document.getElementById("root")!);
root.render(
  <StrictMode>
    <App />
  </StrictMode>
);`;

/**
 * Default index.html
 */
const DEFAULT_HTML = `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Generated App</title>
  </head>
  <body>
    <div id="root"></div>
  </body>
</html>`;

/**
 * Default styles.css
 */
const DEFAULT_STYLES = `* {
  box-sizing: border-box;
}

body {
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen',
    'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue',
    sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#root {
  min-height: 100vh;
}`;

/**
 * Convert generated files to Sandpack files format
 */
export function convertToSandpackFiles(
  generatedFiles: GeneratedFile[]
): SandpackFiles {
  const files: SandpackFiles = {};

  // Add all generated files
  for (const file of generatedFiles) {
    // Normalize path - ensure it starts with /
    let path = file.path;
    if (!path.startsWith("/")) {
      path = "/" + path;
    }

    files[path] = {
      code: file.contents,
    };
  }

  // Ensure required files exist with defaults
  if (!files["/package.json"]) {
    files["/package.json"] = {
      code: JSON.stringify(DEFAULT_PACKAGE_JSON, null, 2),
    };
  }

  if (!files["/public/index.html"] && !files["/index.html"]) {
    files["/public/index.html"] = {
      code: DEFAULT_HTML,
    };
  }

  if (!files["/src/index.tsx"] && !files["/index.tsx"]) {
    files["/src/index.tsx"] = {
      code: DEFAULT_INDEX,
    };
  }

  if (!files["/src/App.tsx"] && !files["/App.tsx"]) {
    files["/src/App.tsx"] = {
      code: DEFAULT_APP,
    };
  }

  if (!files["/src/styles.css"] && !files["/styles.css"]) {
    files["/src/styles.css"] = {
      code: DEFAULT_STYLES,
    };
  }

  return files;
}

/**
 * Validate that files can run in Sandpack
 */
export function validateSandpackFiles(
  files: SandpackFiles
): { valid: boolean; errors: string[] } {
  const errors: string[] = [];

  // Check for entry point
  const hasIndex =
    files["/src/index.tsx"] ||
    files["/index.tsx"] ||
    files["/src/index.ts"] ||
    files["/index.ts"] ||
    files["/src/index.jsx"] ||
    files["/index.jsx"] ||
    files["/src/index.js"] ||
    files["/index.js"];

  if (!hasIndex) {
    errors.push("Missing entry point (index.tsx/index.ts/index.jsx/index.js)");
  }

  // Check for App component
  const hasApp =
    files["/src/App.tsx"] ||
    files["/App.tsx"] ||
    files["/src/App.jsx"] ||
    files["/App.jsx"];

  if (!hasApp) {
    errors.push("Missing App component (App.tsx/App.jsx)");
  }

  // Check for package.json
  if (!files["/package.json"]) {
    errors.push("Missing package.json");
  }

  return {
    valid: errors.length === 0,
    errors,
  };
}

/**
 * Merge file updates into existing files
 */
export function mergeFileUpdate(
  existingFiles: GeneratedFile[],
  update: { path: string; contents?: string; diff?: string }
): GeneratedFile[] {
  const files = [...existingFiles];
  const index = files.findIndex((f) => f.path === update.path);

  if (index >= 0) {
    // Update existing file
    if (update.contents) {
      files[index] = { ...files[index], contents: update.contents };
    } else if (update.diff) {
      // For MVP, treat diff as full replacement
      // In production, you'd apply the actual diff
      files[index] = { ...files[index], contents: update.diff };
    }
  } else {
    // Add new file
    files.push({
      path: update.path,
      contents: update.contents || update.diff || "",
    });
  }

  return files;
}
